import 'package:flutter/material.dart';
import 'package:resume/util/extension/build_context_extension.dart';

class CvInvestarScreen extends StatelessWidget {
  const CvInvestarScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Text(
          context.locale!.cvInvestar,
        ),
        Text(
          '2023-April ~ 2024-November',
        ),
        Text(context.locale!.cvInvestar1),
        Text(
          context.locale!.cvInvestarDailyCoin1,
        ),
        Text(
          context.locale!.cvInvestarDailyCoin2,
        ),
        Text(
          context.locale!.cvInvestarDailyCoin3,
        ),
        Text(
          context.locale!.cvInvestarDailyCoin4,
        ),
        Text(
          context.locale!.cvInvestarDailyCoin5,
        ),
        Text(
          context.locale!.cvInvestarRisingScore1,
        ),
        Text(
          context.locale!.cvInvestarRisingScore2,
        ),
        Text(
          context.locale!.cvInvestarRisingScore3,
        ),
        Text(
          context.locale!.cvInvestarRisingScore4,
        ),
        Text(
          context.locale!.cvInvestarRisingScore5,
        ),
        Text(
          context.locale!.cvInvestarCarousel1,
        ),
        Text(
          context.locale!.cvInvestarCarousel2,
        ),
        Text(
          context.locale!.cvInvestarCarousel3,
        ),
        Text(
          context.locale!.cvInvestarWhale1,
        ),
        Text(
          context.locale!.cvInvestarWhale2,
        ),
        Text(
          context.locale!.cvInvestarWhale3,
        ),
        Text(
          context.locale!.cvInvestarWhale4,
        ),
        Text(
          context.locale!.cvInvestarFavorite1,
        ),
        Text(
          context.locale!.cvInvestarFavorite2,
        ),
        Text(
          context.locale!.cvInvestarCommunity1,
        ),
        Text(
          context.locale!.cvInvestarCommunity2,
        ),
        Text(
          context.locale!.cvInvestarCommunity3,
        ),
        Text(
          context.locale!.cvInvestarMy1,
        ),
        Text(
          context.locale!.cvInvestarMy2,
        ),
        Text(
          context.locale!.cvInvestarMy3,
        ),
        Text(
          context.locale!.cvInvestarSearch1,
        ),
        Text(
          context.locale!.cvInvestarSearch2,
        ),
        Text(
          context.locale!.cvInvestarSearch3,
        ),
        Text(
          context.locale!.cvInvestarGlobal1,
        ),
        Text(
          context.locale!.cvInvestarGlobal2,
        ),
        Text(
          context.locale!.cvInvestarAll,
        ),
      ],
    );
  }
}
